### ISSUE TITLE
#3 - Crear Historias de Usuario

### ISSUE THREAD

**Issue by LorevanBA** [LorevanBA/ScrumSoftware#10]
Planificar y generar las Historias de Usuario necesarias para cumplir con los requerimientos del software a desarrollar.

**Comment by palomamontani** [comment]
Yo como dueño de una pequeña empresa quiero poder tener un stock online para poder revisarlo en todo momento y lugar.

**Comment by Aleejandra2022** [comment]
yo vendedor, quiero saber que productos tengo y cuales me faltan sin revisar a cada rato mi almacén.

**Comment by varelamatias7** [comment]
Yo como empleado de una empresa, quiero llevar a cabo el inventario a diario, semanal o mensual, mediante un sitio web o app y así tener mejor control para la misma.

**Comment by cristianmurua18** [comment]
Yo como usuario quiero poder recuperar o cambiar mi contraseña si no la recuerdo

**Comment by DelfinaDAM** [comment]
#US05: YO como usuario QUIERO tener la opción de acceder a preguntas frecuentes o bien realizar un pregunta en caso de que no este en las preguntas frecuentes PARA solventar mis dudas.

**Comment by Vargas-Veronica** [comment]
#US06  COMO encargado del sector de compras , QUIERO saber cuando esté cerca de la cantidad de productos mínima requerida PARA crear un pedido de compra contemplando el tiempo que tarda el proveedor para no quedarme sin stock.

**Comment by LucasJavierVillalba** [comment]
#US07 COMO empleado de deposito, QUIERO.  poder escanear los productos desde un dispositivo movil PARA no depender de una pc de escritorio

**Comment by LorevanBA** [comment]
#US08 
**Yo como** Encargado de Inventario
**Quiero** disponer de un sistema de control de inventario en tiempo real que permita enviar en archivo pdf o cvs los datos relevados
**Para** dejar de utilizar las tarjetas físicas de conteo y el posterior traspaso a un excel y así poder agilizar los tiempos productivos.

**Comment by LorevanBA** [comment]
#US09
**Yo como** Encargado de Inventario 
**Quiero** un sistema de control de inventario que permita monitorear en tiempo real las entradas, salidas y ajustes de los productos
**Para** llevar un control diario y permanente de manera de reducir los costos de reposición por faltantes, pérdidas y/o robo de productos.

**Comment by LorevanBA** [comment]
#US10
**Yo como** empleado 
**Quiero** que el sistema disponga de un botón "Contar" 
**Para** para ser presionado y realizar el conteo de los productos que fueron seleccionados, para el caso en que el modo escaneo no funcione por alguna cuestión técnica.

**Comment by feveraza** [comment]
#US11
**Yo como** empleado 
**Quiero** poder cargar parcialmente el inventario
**Para** poder continuar con la carga en otro momento sin perder los productos contados, inventariados hasta el momento.

**Comment by feveraza** [comment]
US#11 Yo cómo empleado de un depósito quisiera poder cargar parcialmente el
inventario y poder continuar la carga en otro momento sin perder los
productos contados...
