### ISSUE TITLE
#5 - Generar Mapa de Sitio

### ISSUE THREAD

**Issue by LorevanBA** [LorevanBA/ScrumSoftware#12]
Realizar diagrama que contenga las páginas, videos y otros elementos que tendrá el sitio a desarrollar.

**Comment by Vargas-Veronica** [comment]
![Image](https://user-images.githubusercontent.com/94198041/193643096-7aa632dc-9e24-4cad-9a50-3ae8886c56a2.png)

**Comment by Vargas-Veronica** [comment]
Adjunto Hipótesis de Mapa de Sitio
